import type { Metadata } from "next";
import LegalShell from "../legal-shell";

export const metadata: Metadata = {
  title: "Politique de confidentialité | Cuillère d’Or",
  description: "Traitement des données personnelles et exercice de vos droits auprès de Cuillère d’Or.",
};

export default function PolitiqueConfidentialite() {
  return <LegalShell eyebrow="Protection de vos informations" title="Politique de confidentialité" updated="2 septembre 2026">
    <section><h2>Responsable du traitement</h2><p>Cuillère d’Or, exploitée par Huguette Mvunda-Kilola, est responsable des informations utilisées pour répondre à vos demandes. Vous pouvez nous contacter à l’adresse <a href="mailto:contact@cuilleredor.fr">contact@cuilleredor.fr</a> ou au 8 allée des Bois, 77240 Vert-Saint-Denis.</p></section>
    <section><h2>Données collectées</h2><p>Lors d’une demande de devis ou d’un échange, nous pouvons recevoir vos nom et prénom, adresse e-mail, numéro de téléphone ainsi que les informations nécessaires à l’étude de votre réception : date, lieu, nombre de convives, formule, préférences, contraintes alimentaires et précisions que vous choisissez de transmettre.</p></section>
    <section><h2>Pourquoi utilisons-nous ces données ?</h2><ul><li>répondre à votre demande et préparer une proposition personnalisée ;</li><li>organiser les échanges précontractuels et, si vous acceptez le devis, exécuter la prestation ;</li><li>respecter nos obligations administratives, comptables et légales ;</li><li>assurer le suivi de la relation client et traiter vos demandes.</li></ul><p>Le traitement d’une demande de devis repose principalement sur les mesures précontractuelles prises à votre demande. Les obligations légales et l’exécution du contrat s’appliquent ensuite lorsque vous devenez client.</p></section>
    <section><h2>Formulaires et destinataires</h2><p>Les formulaires de devis intégrés au site sont fournis par Google Forms. Les informations saisies sont transmises à Cuillère d’Or et traitées techniquement par Google selon ses propres conditions. Ne transmettez pas de donnée sensible qui ne serait pas nécessaire à l’étude de votre événement.</p><p><a href="https://policies.google.com/privacy?hl=fr" target="_blank" rel="noreferrer">Consulter les règles de confidentialité de Google</a>.</p></section>
    <section><h2>Durées de conservation</h2><p>Les demandes qui n’aboutissent pas à une prestation sont conservées pendant la durée nécessaire au suivi, puis au maximum trois ans après le dernier contact. Les documents liés à une prestation et à sa facturation sont conservés pendant les durées imposées par la réglementation applicable.</p></section>
    <section><h2>Vos droits</h2><p>Vous pouvez demander l’accès, la rectification, l’effacement ou la limitation de vos données et, lorsque les conditions sont réunies, vous opposer à leur traitement ou demander leur portabilité. Écrivez à <a href="mailto:contact@cuilleredor.fr">contact@cuilleredor.fr</a> en précisant votre demande. Une vérification d’identité pourra être demandée si nécessaire.</p><p>Si vous estimez que vos droits ne sont pas respectés, vous pouvez adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes" target="_blank" rel="noreferrer">CNIL</a>.</p></section>
    <section><h2>Cookies et services tiers</h2><p>Le site n’utilise pas de dispositif publicitaire propre. Son hébergement et les formulaires Google intégrés peuvent toutefois recourir à des éléments techniques nécessaires à leur fonctionnement. En ouvrant un lien externe — notamment WhatsApp, Instagram, TikTok, Google ou OpenAI — vous accédez à un service soumis à sa propre politique de confidentialité.</p></section>
    <section><h2>Sécurité et mise à jour</h2><p>Cuillère d’Or limite l’accès aux informations aux personnes qui en ont besoin pour traiter votre demande et met en œuvre des mesures raisonnables de protection. Cette politique pourra être actualisée pour tenir compte de l’évolution du site, des outils utilisés ou de la réglementation.</p></section>
  </LegalShell>;
}
